# ligue-1-2020-21

Use the "Run" button to execute the code.

In [ ]:
!pip install jovian --upgrade --quiet

In [ ]:
import jovian

In [134]:
# Execute this to save new versions of the notebook
jovian.commit(project="ligue-1-2020-21")

[jovian] Updating notebook "lmnres/ligue-1-2020-21" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/lmnres/ligue-1-2020-21

'https://jovian.ai/lmnres/ligue-1-2020-21'

In [5]:
import pandas as pd
from IPython.display import display
import matplotlib.pyplot as plt
import numpy as np

In [123]:
data_csv = pd.read_csv("data_2020_2021.csv")
#data_csv

In [124]:
data_processed = data_csv.loc[data_csv['home_goal']!="-"]

In [125]:
data_processed

,journee,home,away,scores,home_goal,away_goal,ht_home_goal,ht_away_goal
0,1. Journée,Girondins Bordeaux,FC Nantes,0:0 (0:0),0,0,0,0
1,1. Journée,Dijon FCO,Angers SCO,0:1 (0:1),0,1,0,1
2,1. Journée,Lille OSC,Stade Rennes,1:1 (1:0),1,1,1,0
3,1. Journée,AS Monaco,Stade Reims,2:2 (1:2),2,2,1,2
4,1. Journée,FC Lorient,RC Strasbourg,3:1 (0:1),3,1,0,1
...,...,...,...,...,...,...,...,...
375,38. Journée,FC Nantes,Montpellier HSC,1:2 (1:1),1,2,1,1
376,38. Journée,Stade Reims,Girondins Bordeaux,1:2 (1:1),1,2,1,1
377,38. Journée,Stade Rennes,Nîmes Olympique,2:0 (1:0),2,0,1,0
378,38. Journée,AS Saint-Étienne,Dijon FCO,0:1 (0:1),0,1,0,1
379,38. Journée,RC Strasbourg,FC Lorient,1:1 (1:0),1,1,1,0

In [126]:
data = data_processed.assign(total_goal = pd.to_numeric(data_processed["home_goal"]) + pd.to_numeric(data_processed["away_goal"]))
data

,journee,home,away,scores,home_goal,away_goal,ht_home_goal,ht_away_goal,total_goal
0,1. Journée,Girondins Bordeaux,FC Nantes,0:0 (0:0),0,0,0,0,0
1,1. Journée,Dijon FCO,Angers SCO,0:1 (0:1),0,1,0,1,1
2,1. Journée,Lille OSC,Stade Rennes,1:1 (1:0),1,1,1,0,2
3,1. Journée,AS Monaco,Stade Reims,2:2 (1:2),2,2,1,2,4
4,1. Journée,FC Lorient,RC Strasbourg,3:1 (0:1),3,1,0,1,4
...,...,...,...,...,...,...,...,...,...
375,38. Journée,FC Nantes,Montpellier HSC,1:2 (1:1),1,2,1,1,3
376,38. Journée,Stade Reims,Girondins Bordeaux,1:2 (1:1),1,2,1,1,3
377,38. Journée,Stade Rennes,Nîmes Olympique,2:0 (1:0),2,0,1,0,2
378,38. Journée,AS Saint-Étienne,Dijon FCO,0:1 (0:1),0,1,0,1,1
379,38. Journée,RC Strasbourg,FC Lorient,1:1 (1:0),1,1,1,0,2

In [127]:
total_goals = data["total_goal"]
total_goals.mean()

2.7605263157894737

In [128]:
home_goals = data[["home", "total_goal"]].groupby(by="home").sum()
#home_goals
#home_goals.sort_values(by=["total_goal"],ascending = False)

In [129]:
away_goals = data[["away", "total_goal"]].groupby(by="away").sum()
#away_goals
#away_goals.sort_values(by=["total_goal"],ascending = False)

In [130]:
total_goals = home_goals+away_goals
home_count = 2*data[["home", "total_goal"]].groupby(by="home").count()
total_goals = total_goals/home_count
print("Nombre de buts par matchs")
total_goals.sort_values(by="total_goal",ascending=False)

Nombre de buts par matchs

                     total_goal
home
Olympique Lyon         3.263158
Montpellier HSC        3.210526
AS Monaco              3.105263
FC Lorient             3.105263
Stade Brest            3.052632
Paris Saint-Germain    3.000000
Nîmes Olympique        2.921053
RC Lens                2.868421
RC Strasbourg          2.815789
OGC Nice               2.710526
FC Nantes              2.684211
Olympique Marseille    2.657895
Girondins Bordeaux     2.578947
Dijon FCO              2.578947
Angers SCO             2.578947
AS Saint-Étienne       2.526316
FC Metz                2.421053
Stade Reims            2.421053
Stade Rennes           2.421053
Lille OSC              2.289474

In [132]:
data_sup15 = data.loc[data['total_goal']>1.5]
print("% de match avec + de 1.5 buts saison :", 100*len(data_sup15)/len(data))

% de match avec + de 1.5 buts saison : 78.15789473684211

In [133]:
home_goals = data_sup15[["home", "home_goal"] ].groupby(by="home").count()
home_games = data[["home", "home_goal"] ].groupby(by="home").count()
away_goals = data_sup15[["away", "away_goal"] ].groupby(by="away").count()
away_games = data[["away", "away_goal"] ].groupby(by="away").count()

average_goal_15 = 100*home_goals/home_games
average_goal_15 = average_goal_15.assign(away = 100*away_goals/away_games)
print("probabilite d'avoir plus de 1.5+ buts dans le match selon l'equipe domicile et exterieur")
average_goal_15

probabilite d'avoir plus de 1.5+ buts dans le match selon l'equipe domicile et exterieur

                     home_goal       away
home
AS Monaco            94.736842  63.157895
AS Saint-Étienne     73.684211  73.684211
Angers SCO           73.684211  68.421053
Dijon FCO            57.894737  78.947368
FC Lorient           78.947368  89.473684
FC Metz              84.210526  63.157895
FC Nantes            94.736842  89.473684
Girondins Bordeaux   63.157895  89.473684
Lille OSC            73.684211  73.684211
Montpellier HSC      89.473684  84.210526
Nîmes Olympique      84.210526  84.210526
OGC Nice             84.210526  84.210526
Olympique Lyon       84.210526  78.947368
Olympique Marseille  89.473684  68.421053
Paris Saint-Germain  78.947368  78.947368
RC Lens              73.684211  89.473684
RC Strasbourg        68.421053  89.473684
Stade Brest          89.473684  73.684211
Stade Reims          52.631579  73.684211
Stade Rennes         73.684211  68.421053